#CONTIKI_PROJECT = ml-example
#all: $(CONTIKI_PROJECT)
#MODULES_REL += /home/iot_ubuntu_intel/.local/lib/python3.10/site-packages/emlearn
#TARGET_LIBFILES += -lm
#INC += /home/iot_ubuntu_intel/.local/lib/python3.10/site-packages/emlearn
#CONTIKI = ../../../../../../..
#include $(CONTIKI)/Makefile.include